---
abstract: 'Plack::Middleware::Session::Simple adapter for Mojolicious'
author:
  - 'yowcow <yowcow@cpan.org>'
build_requires:
  Cache::Memory::Simple: '0'
  HTTP::CookieJar: '0'
  HTTP::Request::Common: '0'
  Test::More: '0.98'
  Test::Pretty: '0'
  Test::TCP: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.2.0, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Session-Simple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  MojoX::Session::Simple:
    file: lib/MojoX/Session/Simple.pm
    version: '0.01'
requires:
  Mojolicious: '0'
  Plack::Middleware::Session::Simple: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/yowcow/p5-MojoX-Session-Simple/issues
  homepage: https://github.com/yowcow/p5-MojoX-Session-Simple
  repository: git://github.com/yowcow/p5-MojoX-Session-Simple.git
version: '0.01'
x_authority: cpan:YOWCOW
x_contributors:
  - 'yowcow <yowcow@gmail.com>'
